name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      rfagent:
        env:
          BRANCH_NAME: ${GITHUB_HEAD_REF}
    
    steps:
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo ${BRANCH_NAME}
