name: coucou

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print branch name
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: echo "Branche actuelle => $BRANCH_NAME"
