name: coucou

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print branch name
        env:
          BRANCH_NAME: ${{ env.ref_name }}
        run: echo "Branche actuelle => $BRANCH_NAME"
